PokerRidgeGraceShoppers/graceShopper

.travis.yml
client/components/navbar.js
package.json

Updated the names in yaml, npm package, and navbar.js

updated name in yaml npm package navbar

---

public/index.html

changed index.html

---

norms.md

updated norms file

---

server/db/models/user.js

user model updated

---

server/db/models/product.js

intial product model

---

server/db/models/index.js
server/db/models/transactions.js

adding transaction model

---

server/db/models/transactions.js

fixes transaction export name

---

package-lock.json
server/db/models/index.js
server/db/models/transactions.js

connected models transactions and Product and Users

---

server/db/models/product.js
server/db/models/user.js

deploying app

---

package-lock.json
server/db/models/index.js
server/db/models/reviews.js

~~* [ ] referenced any relevant issues (or none exist)~~
---
Added a model for reviews, what do we think about it?

added reviews model

---

script/data/products.json
script/data/reviews.json
script/data/transactions.json
script/data/users.json
script/seed.js
server/db/models/index.js

finished seed file

---

script/data/transactions.json

added more seeds to transactions

---

script/data/transactions.json

fixed seed file

---

script/seed.spec.js

fixed async seed test

---

server/api/users.js
server/api/users.spec.js

User routes added

---

server/api/users.js

upadted field reducer

---

server/api/index.js
server/api/products.js
server/api/users.js

---
added product back end routes, no tests

added product api routes, no tests yet

---

client/components/auth-form.js
client/components/navbar.js
client/routes.js
client/store/actions/users.js
client/store/index.js
client/store/reducers/index.js
client/store/reducers/user.js
client/store/reducers/user.spec.js

Product views

---

server/db/models/product.spec.js
server/db/models/review.js
server/db/models/review.spec.js
server/db/models/transaction.spec.js
server/db/models/user.js

Further tests

---

server/api/products.js
server/api/userTypeChecker.js
server/api/users.js

added auth funcs to use in backend routes

---

client/app.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/index.js
client/index.js
client/routes.js
client/store/reducers/index.js
client/store/reducers/products.js
package-lock.json

Product pages

---

server/api/index.js
server/api/products.js
server/api/reviews.js
server/api/transactions.js
server/db/models/index.js

~~* [ ] referenced any relevant issues (or none exist)~~
Added back-end routes to db to pull all reviews/transactions along with associated user and products for either model. POST/PUT/DELETE too (on reviews these are only checking for a login, on transactions they are checking for admin status, not just logged in user status).

added review and transaction API routes

---

server/db/models/product.js
server/db/models/user.js

fixes default images

---

client/app.js
client/components/Cart.js
client/components/ProductList.js
client/components/common/ColumnWrap.js
client/components/common/SectionColumn.js
client/components/common/SmallSection.js
client/components/common/index.js
client/store/actions/cart.js
client/store/actions/products.js
client/store/reducers/products.js
public/style.css

made some edits to the product related files

---

client/components/review-form.js
client/store/reducers/review.js
server/api/products.js
server/api/reviews.js
server/api/reviews.spec.js
server/api/transactions.js
server/api/userTypeChecker.js
server/api/users.js
server/api/users.spec.js
server/auth/index.js

* [X ] referenced any relevant issues (or none exist)
---
This commit includes a review form and reducer I'm working on, it's still not working yet. Otherwise this has some API route fixes as per john and now the auth/me now returns user specific JSON

api fixes ignore review-form

---

client/app.js
client/components/Cart.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/common/index.js
client/components/common/sectionRow.js
client/store/actions/cart.js
client/store/actions/products.js
client/store/reducers/cart.js
client/store/reducers/products.js

create remove cart functionality added for guest

---

server/auth/index.js

fixed auth/me route

---

client/components/Review.js
client/components/ReviewForm.js
client/components/SingleProduct.js
client/components/common/SectionRow.js
client/store/actions/reviews.js
client/store/reducers/index.js
client/store/reducers/reviews.js
server/api/reviews.js

* [X ] referenced any relevant issues (or none exist)
---
can now add review to product in product page

added reviewForm to singleProduct view

---

client/components/CheckoutPage/Checkout.js
client/components/CheckoutPage/ShippingAddressForm.js
client/components/CheckoutPage/index.js
client/components/index.js
client/routes.js
package-lock.json
package.json
public/index.html
server/index.js

checkout page working

---

client/store/actions/users.js
script/data/transactions.json
script/data/users.json
script/seed.js
server/auth/index.js
server/db/models/order.js
server/db/models/order.spec.js

updated the seed file to include user orders

---

client/components/Cart/index.js
client/components/index.js
client/routes.js
client/store/actions/cart.js
client/store/actions/users.js
client/store/reducers/cart.js
script/seed.js
server/api/transactions.js
server/api/userTypeChecker.js
server/api/users.js
server/auth/index.js

create read update destroy user_cart

---

client/components/Cart/CartItem.js
client/store/actions/cart.js
server/api/transactions.js

---
_Your PR Notes Here_Guest cart merges with user cart on login

Merge carts

---

client/components/Cart/CartItem.js
client/components/Cart/CartList.js
package-lock.json
server/api/userTypeChecker.js

---
Added inline images to products in cart, small change

Cart with images

---

client/components/ReviewForm.js

Review must be at least 100 characters long or submit button is disabled. The body field should pre-populate with a placeholder saying a review must be over 100 characters long. The Title field should say "review must have a name."

review must be over 100 chars long

---

client/components/SingleProduct.js

~~* [ ] referenced any relevant issues (or none exist)~~
~~### Guidelines~~
~~Please add a description of this Pull Request's motivation, scope, outstanding issues or potential~~
~~alternatives, reasoning behind the current solution, and any other relevant information for posterity.~~
---
~~_Your PR Notes Here_~~
Can now add product by quantity to cart from detailed product page.

addToCartSingleProductPage

---

client/components/UserPage/UserPage.js
client/components/UserPage/index.js

Skeleton of profile page to be completed.

skeleton of progile page

---

server/db/models/index.js

fixed missing getUserData func in server/index

added User.getUserData to models/index

---

server/api/users.js
server/db/models/index.js
server/index.js

fixed git overwritten data

---

client/components/Cart/CartItem.js
client/components/Cart/CartList.js
client/components/CheckoutPage/Checkout.js
client/components/CheckoutPage/ShippingAddressForm.js
client/components/ProductPage/ProductItem.js
client/components/Quantity.js
client/components/ReviewForm.js
client/components/SingleProduct.js
client/components/auth-form.js
package-lock.json
package.json
public/index.html
server/index.js

Semantic ui

---

client/components/Cart/CartItem.js
client/components/Cart/index.js
client/components/CheckoutPage/Checkout.js
client/components/CheckoutPage/ShippingAddressForm.js
client/components/CheckoutPage/index.js
client/components/ProductPage/index.js
client/components/ReviewForm.js
client/components/SingleProduct.js
client/components/UserPage/UserPage.js
client/components/auth-form.js
client/components/navbar.js
client/routes.js
client/store/actions/actionCreators/cart.js
client/store/actions/actionCreators/products.js
client/store/actions/actionCreators/reviews.js
client/store/actions/actionCreators/users.js
client/store/actions/actionTypes.js
client/store/actions/helpers.js
client/store/actions/index.js
client/store/reducers/cart.js
client/store/reducers/products.js
client/store/reducers/reviews.js
client/store/reducers/user.js
client/store/reducers/user.spec.js
server/api/orders.js
server/index.js

File restructure actions
